# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=50)),
                ('cod_fabrica', models.IntegerField(blank=True, null=True)),
                ('cod_marca', models.CharField(blank=True, max_length=5)),
                ('cod_tipo', models.IntegerField(blank=True, null=True)),
                ('cod_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tv', models.CharField(blank=True, max_length=3)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('valuacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('concepto_bonificacion', models.CharField(blank=True, max_length=100)),
                ('porcentaje_bonificacion', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('razonsocial', models.CharField(blank=True, max_length=50)),
                ('dni', models.IntegerField()),
                ('cuit', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=8)),
                ('fechaalta', models.DateField()),
                ('id_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.auto')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.persona')),
            ],
        ),
        migrations.AddField(
            model_name='impuesto',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.vehiculo'),
        ),
    ]
