# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='valuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=3)),
                ('cod_fabrica', models.IntegerField(blank=True)),
                ('cod_marca', models.CharField(max_length=5)),
                ('cod_tipo', models.IntegerField()),
                ('cod_modelo', models.IntegerField()),
                ('tv', models.CharField(max_length=3)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('val_okm', models.IntegerField()),
                ('val_2016', models.IntegerField()),
                ('val_2015', models.IntegerField()),
                ('val_2014', models.IntegerField()),
                ('val_2013', models.IntegerField()),
                ('val_2012', models.IntegerField()),
                ('val_2011', models.IntegerField()),
                ('val_2010', models.IntegerField()),
                ('val_2009', models.IntegerField()),
                ('val_2008', models.IntegerField()),
                ('val_2007', models.IntegerField()),
                ('val_2006', models.IntegerField()),
                ('val_2005', models.IntegerField()),
                ('val_2004', models.IntegerField()),
                ('val_2003', models.IntegerField()),
                ('val_2002', models.IntegerField()),
                ('val_2001', models.IntegerField()),
                ('val_2000', models.IntegerField()),
                ('val_1999', models.IntegerField()),
                ('val_1998', models.IntegerField()),
                ('val_1997', models.IntegerField()),
                ('val_1996', models.IntegerField()),
                ('val_1995', models.IntegerField()),
                ('val_1994', models.IntegerField()),
                ('val_1993', models.IntegerField()),
            ],
        ),
    ]
