# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuacion', '0002_auto_20171117_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuacion',
            name='val_okm',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
