# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuacion', '0006_auto_20180615_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1993',
            new_name='val_10',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1994',
            new_name='val_11',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1995',
            new_name='val_12',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1996',
            new_name='val_13',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1997',
            new_name='val_14',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1998',
            new_name='val_15',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_1999',
            new_name='val_16',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2000',
            new_name='val_17',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2001',
            new_name='val_18',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2002',
            new_name='val_19',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2003',
            new_name='val_20',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2004',
            new_name='val_21',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2005',
            new_name='val_22',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2006',
            new_name='val_23',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2007',
            new_name='val_24',
        ),
        migrations.RenameField(
            model_name='valuacion',
            old_name='val_2008',
            new_name='val_9',
        ),
    ]
