# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuacion', '0007_auto_20180615_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuacion',
            name='cod_modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuacion',
            name='origen',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
